add-controllers
pavp1/java-shareit pull request #1
Opened 2023-07-11 20:33 UTC by pavp1

2023-07-12 18:39 UTC, alexache requested changes

2023-07-12 18:39 UTC, alexache commented on pom.xml
> +		<!--		<dependency>-->
Закомментированный код лучше убирать

2023-07-12 18:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/exception/handler/ControllerAdvice.java
> +        e.printStackTrace();
Почему бы не писать в полноценный логгер?

2023-07-12 18:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    ) {
Немного не каноничный для Java стиль с переносами скобок. Принята круглая скобка на той же строке, что и последний аргумент

2023-07-12 18:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    Optional<Item> getItemById(Long itemId) {
Не хватает модификатора доступа

2023-07-12 18:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public Item createItem(Item item) {
Не хватает @Override у методов

2023-07-12 18:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        if (existingItemOpt.isEmpty()) {
Проще пользоваться у Optional методом orElseThrow

2023-07-12 18:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        searchText = "%" + searchText + "%";
Немного нелогичное для сервиса, не знающего о том, как работает сторадж

2023-07-12 18:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    Long id;
Не хватает модификаторов доступа у полей

2023-07-12 18:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    Long id;
Не хватает модификаторов доступа + для его валидации в модели?

2023-07-12 18:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +        System.out.println("WE ARE IN CREATE USER");
Отладочные сообщения лучше убирать

2023-07-12 18:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +    Optional<User> getUserById(Long userId) {
Повторные комментарии про модификаторы доступа в схожих классах

2023-07-12 18:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserRepository.java
> +//    private void checkUserNotExistByEmail(String email) {
Не должно оставаться закомментированного кода

2023-07-12 18:39 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +@Component
Нужно ли и Service, и Component?

2023-07-12 20:30 UTC, pavp1 commented
Большое спасибо за столь развёрнутые комметрарии по делу!

2023-07-13 16:32 UTC, alexache approved these changes

2023-07-13 16:32 UTC, alexache commented on src/main/java/ru/practicum/shareit/user/UserService.java
>  public class UserService {
На будущее это тоже можно бы разделить на интерфейс и реализацию

2023-07-18 16:40 UTC, merged